### ISSUE TITLE
Tutki datan siirtoa paikalliselta pilveen

### ISSUE THREAD

**Issue by stlgithub** [stlgithub/BearIT-Data#24]
Related to #4

**Comment by sillaka1** [comment]
Datan siirto onnistuu paikalliseslta pilveen MySQL Workbenchin kautta, jolloin lokaaliserveri tulee olla päällä. Jos yhteys katkaistaan lokaalilta, niin silloin myös pilvipalvelun tietokanta on saamattomissa. 

Jos halutaan, että tietokanta on koko ajan aktiivisena, niin silloin EC2 instanssi tulee olla päällä AWS'ssä ja tietokannan Amazonin RDS-palvelussa. Dumppi tulee siirtää RDS:lle, jos halutaan tietokannan olevan saatavilla ilman lokaalia serveriä.
